version: "3"
services:
  bot:
    #               discord bot with cog
    container_name: dcbwc
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ".:/usr/src/"