version: "3"
services:
  bot:
    #               discord bot with cog
    container_name: dcbwc
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./bot:/usr/src/bot